/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    roles: Role;
    permissions: Permission;
    media: Media;
    'audit-logs': AuditLog;
    categories: Category;
    tags: Tag;
    pages: Page;
    ministries: Ministry;
    missions: Mission;
    leadership: Leadership;
    events: Event;
    'event-registrations': EventRegistration;
    sermons: Sermon;
    devotionals: Devotional;
    books: Book;
    resources: Resource;
    'blog-posts': BlogPost;
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'homepage-layout': HomepageLayout;
    messages: Message;
    'prayer-requests': PrayerRequest;
    'counseling-requests': CounselingRequest;
    'volunteer-applications': VolunteerApplication;
    partners: Partner;
    testimonials: Testimonial;
    'newsletter-subscribers': NewsletterSubscriber;
    donations: Donation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    missions: MissionsSelect<false> | MissionsSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    devotionals: DevotionalsSelect<false> | DevotionalsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'homepage-layout': HomepageLayoutSelect<false> | HomepageLayoutSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'counseling-requests': CounselingRequestsSelect<false> | CounselingRequestsSelect<true>;
    'volunteer-applications': VolunteerApplicationsSelect<false> | VolunteerApplicationsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'it' | 'es') | ('en' | 'fr' | 'it' | 'es')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr' | 'it' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for the *.jbim-platform.app subdomain
   */
  slug: string;
  /**
   * Custom domains resolved to this tenant, e.g. justbelieveintmissions.org
   */
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  branding?: {
    logoLight?: (number | null) | Media;
    logoDark?: (number | null) | Media;
    colors?: {
      /**
       * Hex, e.g. #10182E (Ink)
       */
      primary?: string | null;
      /**
       * Hex, e.g. #232C55 (Indigo)
       */
      secondary?: string | null;
      /**
       * Hex, e.g. #C9973C (Gold)
       */
      accent?: string | null;
    };
  };
  locales?: {
    defaultLocale?: ('en' | 'fr' | 'it' | 'es') | null;
    supportedLocales?: ('en' | 'fr' | 'it' | 'es')[] | null;
  };
  /**
   * Per-tenant Paystack config — never a shared platform-wide account. Use test-mode keys (pk_test_/sk_test_) until this tenant is ready to accept live donations.
   */
  paystack?: {
    /**
     * Safe to expose client-side — used to open the Paystack checkout popup (pk_test_... or pk_live_...)
     */
    publicKey?: string | null;
    /**
     * Server-side only — verifies transactions and creates recurring Plans. Never sent to the browser (sk_test_... or sk_live_...)
     */
    secretKey?: string | null;
  };
  /**
   * Per-tenant Stripe config — a second donation option alongside Paystack, donor picks at checkout (2026-08-11). Use test-mode keys until this tenant is ready to accept live donations.
   */
  stripe?: {
    /**
     * Not currently used server-side — Checkout Sessions are created and redirected to entirely server-side, no Stripe.js on the client. Stored for parity/future use only (pk_test_... or pk_live_...)
     */
    publishableKey?: string | null;
    /**
     * Server-side only — creates and retrieves Checkout Sessions. Never sent to the browser (sk_test_... or sk_live_...)
     */
    secretKey?: string | null;
    /**
     * From the Stripe Dashboard when registering https://<domain>/api/webhooks/stripe/<tenant-slug> as an endpoint — verifies the Stripe-Signature header (whsec_...). Different from secretKey; Stripe signs webhooks with a per-endpoint secret, not the account key.
     */
    webhookSecret?: string | null;
  };
  /**
   * Suspending/deleting a tenant is Platform Super Admin-only and audit-logged (FR-TENANT-05)
   */
  status?: ('active' | 'suspended') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant: number | Tenant;
  /**
   * Required for accessibility (NFR-06, WCAG 2.1 AA). Localized per NFR-07.
   */
  alt: string;
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  /**
   * Cross-tenant operator access (blueinctech). Platform Super Admin-only to set.
   */
  isPlatformSuperAdmin?: boolean | null;
  tenantMemberships?:
    | {
        tenant: number | Tenant;
        role: number | Role;
        id?: string | null;
      }[]
    | null;
  twoFactor?: {
    enabled?: boolean | null;
    /**
     * TOTP secret, encrypted at rest — never exposed to the admin UI
     */
    secret?: string | null;
  };
  status?: ('active' | 'deactivated') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Leave empty only for platform-scope roles (Platform Super Admin tooling)
   */
  tenant?: (number | null) | Tenant;
  name: string;
  permissions?: (number | Permission)[] | null;
  /**
   * Seeded default role — editable, but protected from deletion
   */
  isSystemRole?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  /**
   * e.g. "sermons.publish", "donations.view" — dot-namespaced module.action
   */
  key: string;
  /**
   * Groups this permission in the Role-builder UI (e.g. "Sermons", "Donations")
   */
  module: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * Null for platform-scope actions (e.g. tenant creation itself)
   */
  tenant?: (number | null) | Tenant;
  user?: (number | null) | User;
  action: 'create' | 'update' | 'delete';
  collectionSlug: string;
  documentId: string;
  /**
   * Redacted of secrets (password, 2FA secret, etc.) before storage
   */
  previousValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Redacted of secrets (password, 2FA secret, etc.) before storage
   */
  newValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant: number | Tenant;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant: number | Tenant;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant: number | Tenant;
  title: string;
  slug: string;
  blocks?:
    | {
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  tenant: number | Tenant;
  name: string;
  slug: string;
  /**
   * One sentence for the Ministries overview page and homepage teasers. The full description below is for the individual ministry page only — never render it in a card grid.
   */
  shortDescription?: string | null;
  /**
   * Full description — individual ministry page only.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leader?: (number | null) | Leadership;
  image?: (number | null) | Media;
  order?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  tenant: number | Tenant;
  name: string;
  title?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  /**
   * Books.author defaults to whichever record has this set
   */
  isFounder?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions".
 */
export interface Mission {
  id: number;
  tenant: number | Tenant;
  name: string;
  slug: string;
  /**
   * One sentence for overview/listing contexts. The full description below is for the individual mission page only.
   */
  shortDescription?: string | null;
  /**
   * Full description — individual mission page only.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  phase?: ('planning' | 'active' | 'completed') | null;
  startDate?: string | null;
  endDate?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  tenant: number | Tenant;
  title: string;
  slug: string;
  type: 'in-person' | 'online' | 'hybrid';
  startDate: string;
  endDate?: string | null;
  /**
   * For in-person/hybrid events
   */
  location?: string | null;
  speaker?: string | null;
  /**
   * For online/hybrid events — external embed only, see docs/02-architecture.md §8
   */
  livestreamUrl?: string | null;
  /**
   * Leave empty for uncapped — EventRegistrations only auto-waitlists once this is set (FR-EVT-06)
   */
  capacity?: number | null;
  registrationOpen?: string | null;
  registrationClose?: string | null;
  materials?: (number | Media)[] | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  tenant: number | Tenant;
  event: number | Event;
  name: string;
  email: string;
  phone?: string | null;
  registeredAt?: string | null;
  checkedIn?: boolean | null;
  /**
   * Set automatically once event.capacity is reached (FR-EVT-06)
   */
  waitlisted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  tenant: number | Tenant;
  title: string;
  type: 'audio' | 'video' | 'written';
  speaker?: string | null;
  scripture?: string[] | null;
  topics?: (number | Category)[] | null;
  /**
   * For self-hosted audio/video, mutually exclusive with embedUrl
   */
  mediaFile?: (number | null) | Media;
  /**
   * For an external embed (e.g. YouTube), mutually exclusive with mediaFile
   */
  embedUrl?: string | null;
  date: string;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devotionals".
 */
export interface Devotional {
  id: number;
  tenant: number | Tenant;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cadence: 'daily' | 'weekly' | 'series';
  /**
   * Groups this devotional under a parent series entry
   */
  series?: (number | null) | Devotional;
  date: string;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  tenant: number | Tenant;
  title: string;
  slug: string;
  category?: (number | null) | Category;
  featured?: boolean | null;
  author?: (number | null) | Leadership;
  coverImage?: (number | null) | Media;
  /**
   * Mutually exclusive with coverImage+file, for an external retailer/listing link
   */
  externalLink?: string | null;
  description?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  tenant: number | Tenant;
  title: string;
  author?: (number | null) | Leadership;
  coverImage?: (number | null) | Media;
  externalLink?: string | null;
  description?: string | null;
  type: 'study-guide' | 'prayer-guide' | 'discipleship-manual' | 'teaching-notes';
  /**
   * Requires visitor contact info to download
   */
  gated?: boolean | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  tenant: number | Tenant;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  /**
   * One or two sentences for cards/listing contexts — the full post body is for the post page only.
   */
  excerpt?: string | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  author?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null);
  publishedAt?: string | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant: number | Tenant;
  siteName: string;
  contactEmail?: string | null;
  contactPhone?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'x' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  notificationPreferences?: {
    newPrayerRequest?: boolean | null;
    newCounselingRequest?: boolean | null;
    newVolunteerApplication?: boolean | null;
    newEventRegistration?: boolean | null;
    newDonation?: boolean | null;
  };
  analytics?: {
    /**
     * Google Analytics
     */
    gaId?: string | null;
    /**
     * Google Search Console
     */
    gscId?: string | null;
    /**
     * Microsoft Clarity
     */
    clarityId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  tenant: number | Tenant;
  items?:
    | {
        label: string;
        link: string;
        order?: number | null;
        children?:
          | {
              label: string;
              link: string;
              order?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tenant: number | Tenant;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'x' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-layout".
 */
export interface HomepageLayout {
  id: number;
  tenant: number | Tenant;
  sections?:
    | {
        blockType:
          | 'Hero'
          | 'QuickLinksBar'
          | 'FoundationStatement'
          | 'WelcomeMessage'
          | 'MinistryPathways'
          | 'PhotoCaptionGrid'
          | 'MinistryFeatureGrid'
          | 'FeaturedSermons'
          | 'FeaturedEvents'
          | 'FeaturedBooks'
          | 'MinistriesOverview'
          | 'HeroMediaStrip'
          | 'BlogSpotlight'
          | 'Prayer'
          | 'Testimonials'
          | 'PartnershipInvitation'
          | 'NewsletterSignup'
          | 'RichText'
          | 'CTA';
        order?: number | null;
        visible?: boolean | null;
        /**
         * Per-block instance config — shape depends on blockType
         */
        config?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  tenant: number | Tenant;
  name: string;
  email: string;
  subject: string;
  message: string;
  status?: ('new' | 'read' | 'in-progress' | 'resolved' | 'archived') | null;
  assignedTo?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  tenant: number | Tenant;
  name: string;
  contact: string;
  requestText: string;
  isPrivate?: boolean | null;
  status?: ('new' | 'in-prayer' | 'answered' | 'closed') | null;
  assignedTo?: (number | null) | User;
  /**
   * Staff-only — never exposed on public read
   */
  internalNotes?:
    | {
        author?: (number | null) | User;
        note: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counseling-requests".
 */
export interface CounselingRequest {
  id: number;
  tenant: number | Tenant;
  name: string;
  contact: string;
  requestText: string;
  type: 'biblical' | 'family' | 'marriage' | 'individual';
  isPrivate?: boolean | null;
  status?: ('new' | 'in-prayer' | 'answered' | 'closed') | null;
  assignedTo?: (number | null) | User;
  /**
   * Staff-only — never exposed on public read
   */
  internalNotes?:
    | {
        author?: (number | null) | User;
        note: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-applications".
 */
export interface VolunteerApplication {
  id: number;
  tenant: number | Tenant;
  name: string;
  contact: string;
  areaOfInterest?: string | null;
  message?: string | null;
  status?: ('new' | 'reviewing' | 'approved' | 'declined') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  tenant: number | Tenant;
  /**
   * Leave empty for an individual partner — use individualName instead
   */
  orgName?: string | null;
  individualName?: string | null;
  contact: string;
  engagementType: 'prayer' | 'financial' | 'volunteer' | 'project-sponsor' | 'mission-trip';
  /**
   * Optional — shown in the public "Partner Logos" display
   */
  logo?: (number | null) | Media;
  status?: ('new' | 'active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant: number | Tenant;
  submitterName: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  photo?: (number | null) | Media;
  status?: ('submitted' | 'approved' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  tenant: number | Tenant;
  email: string;
  /**
   * Double opt-in confirmation, per docs/02-architecture.md §1 (Resend)
   */
  confirmed?: boolean | null;
  confirmedAt?: string | null;
  /**
   * Presence of a value = inactive subscriber
   */
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  tenant: number | Tenant;
  /**
   * Empty if the donor chose to give anonymously
   */
  donorName?: string | null;
  donorEmail?: string | null;
  /**
   * Major currency unit (e.g. 5000 NGN, not kobo) — converted from Paystack's subunit amount on verify
   */
  amount: number;
  currency: 'NGN' | 'USD';
  /**
   * Only populated when currency is already USD (amount === usdAmount). No live FX rate is integrated, so NGN donations leave this blank rather than show a fabricated conversion — see docs/00-decisions-log.md.
   */
  usdAmount?: number | null;
  fund: 'general' | 'mission-projects' | 'child-sponsorship' | 'special-campaign';
  /**
   * Which gateway processed this charge — determines which reference field below is populated
   */
  processor: 'paystack' | 'stripe';
  /**
   * Set only when processor is Paystack. NULLs don't collide under a unique constraint, so Stripe rows leaving this blank is fine.
   */
  paystackReference?: string | null;
  /**
   * Set only when this Paystack charge belongs to a recurring Plan (monthly giving)
   */
  paystackSubscriptionCode?: string | null;
  /**
   * Set only when processor is Stripe — the Checkout Session id, this processor's idempotency key
   */
  stripeSessionId?: string | null;
  /**
   * Set only when this Stripe charge belongs to a subscription (monthly giving)
   */
  stripeSubscriptionId?: string | null;
  status: 'completed' | 'refunded' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'missions';
        value: number | Mission;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'devotionals';
        value: number | Devotional;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'homepage-layout';
        value: number | HomepageLayout;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'counseling-requests';
        value: number | CounselingRequest;
      } | null)
    | ({
        relationTo: 'volunteer-applications';
        value: number | VolunteerApplication;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  branding?:
    | T
    | {
        logoLight?: T;
        logoDark?: T;
        colors?:
          | T
          | {
              primary?: T;
              secondary?: T;
              accent?: T;
            };
      };
  locales?:
    | T
    | {
        defaultLocale?: T;
        supportedLocales?: T;
      };
  paystack?:
    | T
    | {
        publicKey?: T;
        secretKey?: T;
      };
  stripe?:
    | T
    | {
        publishableKey?: T;
        secretKey?: T;
        webhookSecret?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  isPlatformSuperAdmin?: T;
  tenantMemberships?:
    | T
    | {
        tenant?: T;
        role?: T;
        id?: T;
      };
  twoFactor?:
    | T
    | {
        enabled?: T;
        secret?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  permissions?: T;
  isSystemRole?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  key?: T;
  module?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  previousValue?: T;
  newValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  leader?: T;
  image?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions_select".
 */
export interface MissionsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  location?: T;
  phase?: T;
  startDate?: T;
  endDate?: T;
  image?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  title?: T;
  bio?: T;
  photo?: T;
  isFounder?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  type?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  speaker?: T;
  livestreamUrl?: T;
  capacity?: T;
  registrationOpen?: T;
  registrationClose?: T;
  materials?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  tenant?: T;
  event?: T;
  name?: T;
  email?: T;
  phone?: T;
  registeredAt?: T;
  checkedIn?: T;
  waitlisted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  type?: T;
  speaker?: T;
  scripture?: T;
  topics?: T;
  mediaFile?: T;
  embedUrl?: T;
  date?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devotionals_select".
 */
export interface DevotionalsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  body?: T;
  cadence?: T;
  series?: T;
  date?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  category?: T;
  featured?: T;
  author?: T;
  coverImage?: T;
  externalLink?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  author?: T;
  coverImage?: T;
  externalLink?: T;
  description?: T;
  type?: T;
  gated?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  body?: T;
  slug?: T;
  excerpt?: T;
  categories?: T;
  tags?: T;
  author?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  siteName?: T;
  contactEmail?: T;
  contactPhone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  notificationPreferences?:
    | T
    | {
        newPrayerRequest?: T;
        newCounselingRequest?: T;
        newVolunteerApplication?: T;
        newEventRegistration?: T;
        newDonation?: T;
      };
  analytics?:
    | T
    | {
        gaId?: T;
        gscId?: T;
        clarityId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tenant?: T;
  items?:
    | T
    | {
        label?: T;
        link?: T;
        order?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              order?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tenant?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-layout_select".
 */
export interface HomepageLayoutSelect<T extends boolean = true> {
  tenant?: T;
  sections?:
    | T
    | {
        blockType?: T;
        order?: T;
        visible?: T;
        config?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  contact?: T;
  requestText?: T;
  isPrivate?: T;
  status?: T;
  assignedTo?: T;
  internalNotes?:
    | T
    | {
        author?: T;
        note?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counseling-requests_select".
 */
export interface CounselingRequestsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  contact?: T;
  requestText?: T;
  type?: T;
  isPrivate?: T;
  status?: T;
  assignedTo?: T;
  internalNotes?:
    | T
    | {
        author?: T;
        note?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-applications_select".
 */
export interface VolunteerApplicationsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  contact?: T;
  areaOfInterest?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  tenant?: T;
  orgName?: T;
  individualName?: T;
  contact?: T;
  engagementType?: T;
  logo?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  submitterName?: T;
  content?: T;
  photo?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  tenant?: T;
  email?: T;
  confirmed?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  tenant?: T;
  donorName?: T;
  donorEmail?: T;
  amount?: T;
  currency?: T;
  usdAmount?: T;
  fund?: T;
  processor?: T;
  paystackReference?: T;
  paystackSubscriptionCode?: T;
  stripeSessionId?: T;
  stripeSubscriptionId?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}